# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/git/libhotstuff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/git/libhotstuff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /root/git/libhotstuff && $(CMAKE_COMMAND) -E cmake_progress_start /root/git/libhotstuff/CMakeFiles /root/git/libhotstuff/bls/CMakeFiles/progress.marks
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/git/libhotstuff/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /root/git/libhotstuff && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
bls/CMakeFiles/bls384.dir/rule:
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/CMakeFiles/bls384.dir/rule
.PHONY : bls/CMakeFiles/bls384.dir/rule

# Convenience name for target.
bls384: bls/CMakeFiles/bls384.dir/rule

.PHONY : bls384

# fast build rule for target.
bls384/fast:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384.dir/build.make bls/CMakeFiles/bls384.dir/build
.PHONY : bls384/fast

# Convenience name for target.
bls/CMakeFiles/bls384_256.dir/rule:
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/CMakeFiles/bls384_256.dir/rule
.PHONY : bls/CMakeFiles/bls384_256.dir/rule

# Convenience name for target.
bls384_256: bls/CMakeFiles/bls384_256.dir/rule

.PHONY : bls384_256

# fast build rule for target.
bls384_256/fast:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384_256.dir/build.make bls/CMakeFiles/bls384_256.dir/build
.PHONY : bls384_256/fast

# Convenience name for target.
bls/CMakeFiles/bls256.dir/rule:
	cd /root/git/libhotstuff && $(MAKE) -f CMakeFiles/Makefile2 bls/CMakeFiles/bls256.dir/rule
.PHONY : bls/CMakeFiles/bls256.dir/rule

# Convenience name for target.
bls256: bls/CMakeFiles/bls256.dir/rule

.PHONY : bls256

# fast build rule for target.
bls256/fast:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls256.dir/build.make bls/CMakeFiles/bls256.dir/build
.PHONY : bls256/fast

src/bls_c256.o: src/bls_c256.cpp.o

.PHONY : src/bls_c256.o

# target to build an object file
src/bls_c256.cpp.o:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls256.dir/build.make bls/CMakeFiles/bls256.dir/src/bls_c256.cpp.o
.PHONY : src/bls_c256.cpp.o

src/bls_c256.i: src/bls_c256.cpp.i

.PHONY : src/bls_c256.i

# target to preprocess a source file
src/bls_c256.cpp.i:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls256.dir/build.make bls/CMakeFiles/bls256.dir/src/bls_c256.cpp.i
.PHONY : src/bls_c256.cpp.i

src/bls_c256.s: src/bls_c256.cpp.s

.PHONY : src/bls_c256.s

# target to generate assembly for a file
src/bls_c256.cpp.s:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls256.dir/build.make bls/CMakeFiles/bls256.dir/src/bls_c256.cpp.s
.PHONY : src/bls_c256.cpp.s

src/bls_c384.o: src/bls_c384.cpp.o

.PHONY : src/bls_c384.o

# target to build an object file
src/bls_c384.cpp.o:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384.dir/build.make bls/CMakeFiles/bls384.dir/src/bls_c384.cpp.o
.PHONY : src/bls_c384.cpp.o

src/bls_c384.i: src/bls_c384.cpp.i

.PHONY : src/bls_c384.i

# target to preprocess a source file
src/bls_c384.cpp.i:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384.dir/build.make bls/CMakeFiles/bls384.dir/src/bls_c384.cpp.i
.PHONY : src/bls_c384.cpp.i

src/bls_c384.s: src/bls_c384.cpp.s

.PHONY : src/bls_c384.s

# target to generate assembly for a file
src/bls_c384.cpp.s:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384.dir/build.make bls/CMakeFiles/bls384.dir/src/bls_c384.cpp.s
.PHONY : src/bls_c384.cpp.s

src/bls_c384_256.o: src/bls_c384_256.cpp.o

.PHONY : src/bls_c384_256.o

# target to build an object file
src/bls_c384_256.cpp.o:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384_256.dir/build.make bls/CMakeFiles/bls384_256.dir/src/bls_c384_256.cpp.o
.PHONY : src/bls_c384_256.cpp.o

src/bls_c384_256.i: src/bls_c384_256.cpp.i

.PHONY : src/bls_c384_256.i

# target to preprocess a source file
src/bls_c384_256.cpp.i:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384_256.dir/build.make bls/CMakeFiles/bls384_256.dir/src/bls_c384_256.cpp.i
.PHONY : src/bls_c384_256.cpp.i

src/bls_c384_256.s: src/bls_c384_256.cpp.s

.PHONY : src/bls_c384_256.s

# target to generate assembly for a file
src/bls_c384_256.cpp.s:
	cd /root/git/libhotstuff && $(MAKE) -f bls/CMakeFiles/bls384_256.dir/build.make bls/CMakeFiles/bls384_256.dir/src/bls_c384_256.cpp.s
.PHONY : src/bls_c384_256.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... bls384"
	@echo "... bls384_256"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... bls256"
	@echo "... rebuild_cache"
	@echo "... src/bls_c256.o"
	@echo "... src/bls_c256.i"
	@echo "... src/bls_c256.s"
	@echo "... src/bls_c384.o"
	@echo "... src/bls_c384.i"
	@echo "... src/bls_c384.s"
	@echo "... src/bls_c384_256.o"
	@echo "... src/bls_c384_256.i"
	@echo "... src/bls_c384_256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /root/git/libhotstuff && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

